# netlify.toml

# Build settings
[build]
  command = "CI= npm run build"
  publish = "build"
  functions = "functions"  # Specify the Netlify Functions directory

# Redirects for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
